### ISSUE TITLE
Compatibility with Druid 0.22 - Missing bucketStart method

### ISSUE THREAD

**Issue by schapirama** [Zenysis/druid-arbitrary-granularity#4]
Hello,

I have recently upgraded my Druid cluster (using Imply's version, to their latest, which I think runs Druid 0.22), and the Arbitrary Granularitiy plugin stopped working. I get the following:

```
com.fasterxml.jackson.core.JsonParseException: Unknown exception: (on ip-...l:8283): Invalid type marker byte 0x3c for expected value token\n at [Source: (SequenceInputStream); line: -1, column: 1]
```

In every historical, we get this:

```
[2021-12-13T12:55:49+01:00] (i-04839be8830b290c0/historical.log) 2021-12-13T11:55:49,093 ERROR [qtp962784388-135] 

com.sun.jersey.spi.container.ContainerResponse - The exception contained within MappableContainerException could not be mapped to a response, re-throwing to the HTTP container

java.lang.AbstractMethodError: org.apache.druid.java.util.common.granularity.Granularity.bucketStart(J)J
    at org.apache.druid.query.ResultGranularTimestampComparator.compare(ResultGranularTimestampComparator.java:45) ~[druid-processing-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.query.ResultGranularTimestampComparator.compare(ResultGranularTimestampComparator.java:31) ~[druid-processing-2021.11.1-iap.jar:2021.11.1-iap]
    at com.google.common.collect.ComparatorOrdering.compare(ComparatorOrdering.java:38) ~[guava-16.0.1.jar:?]
    at org.apache.druid.common.guava.CombiningSequence$CombiningYieldingAccumulator.accumulate(CombiningSequence.java:220) ~[druid-core-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.java.util.common.guava.BaseSequence.makeYielder(BaseSequence.java:90) ~[druid-core-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.java.util.common.guava.BaseSequence.toYielder(BaseSequence.java:69) ~[druid-core-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.common.guava.CombiningSequence.toYielder(CombiningSequence.java:78) ~[druid-core-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.java.util.common.guava.MappedSequence.toYielder(MappedSequence.java:49) ~[druid-core-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:88) ~[druid-core-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:84) ~[druid-core-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.query.CPUTimeMetricQueryRunner$1.wrap(CPUTimeMetricQueryRunner.java:78) ~[druid-processing-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.java.util.common.guava.WrappingSequence.toYielder(WrappingSequence.java:83) ~[druid-core-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.java.util.common.guava.Yielders.each(Yielders.java:32) ~[druid-core-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.server.QueryResource.doPost(QueryResource.java:224) ~[druid-server-2021.11.1-iap.jar:2021.11.1-iap]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
...
```

and finally an error in the broker:

```
[2021-12-13T12:55:49+01:00] (i-033d7c3a7667fd592/broker.log) 2021-12-13T11:55:49,107 WARN [ForkJoinPool-1-worker-1] org.apache.druid.client.JsonParserIterator - Query [8d2f0b0d-e0e5-40ae-8254-b81566b2d50d] to host [ip-10-50-35-109.us-west-2.compute.internal:8283] interrupted
com.fasterxml.jackson.core.JsonParseException: Invalid type marker byte 0x3c for expected value token
 at [Source: (SequenceInputStream); line: -1, column: 1]
    at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840) ~[jackson-core-2.10.5.jar:2.10.5]
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712) ~[jackson-core-2.10.5.jar:2.10.5]
    at com.fasterxml.jackson.dataformat.smile.SmileParser.nextToken(SmileParser.java:494) ~[jackson-dataformat-smile-2.10.5.jar:2.10.5]
    at org.apache.druid.client.JsonParserIterator.init(JsonParserIterator.java:178) [druid-server-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.client.JsonParserIterator.hasNext(JsonParserIterator.java:93) [druid-server-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.java.util.common.guava.BaseSequence.makeYielder(BaseSequence.java:89) [druid-core-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.java.util.common.guava.BaseSequence.toYielder(BaseSequence.java:69) [druid-core-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.java.util.common.guava.MappedSequence.toYielder(MappedSequence.java:49) [druid-core-2021.11.1-iap.jar:2021.11.1-iap]
    at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$ResultBatch.fromSequence(ParallelMergeCombiningSequence.java:875) [druid-core-2021.11.1-iap.jar:2021.11.1-iap]
```

The query is as follows: 

```
{
    "dataSource": "xxx",
    "queryType": "timeseries",
    "intervals": "2021-12-01T00:00:00.000Z/2021-12-31T00:00:00.000Z",
    "granularity": {
        "type": "arbitrary",
        "intervals": [
            "2021-12-01/2021-12-05",
            "2021-12-06/2021-12-14",
            "2021-12-15/2021-12-28"
        ]
    },
    "aggregations": [
        {
            "type": "longSum",
            "fieldName": "event_count",
            "name": "event_count"
        }
    ]
}
```

and it used to work fine with older versions of Druid.

I see that in 2017 there was a patch to add a `DateTime bucketStart` method to the Granulatity class. However, Druid recently (beginning of 2021) added a `long bucketStart` method, here: https://github.com/apache/druid/pull/10904 -- https://github.com/apache/druid/blame/e53c3e80ca246c0bc9efd18d23858b791eb6e1a2/core/src/main/java/org/apache/druid/java/util/common/granularity/Granularity.java#L142

Is the library still being supported? Would it be possible to request a patch for it? 

Thanks!

**Comment by capistrant** [comment]
#3 should get it working. Although it doesn’t take advantage of the upstream Druid implementation of this method that looks to make the code more efficient with less casting of dates to different types.

**Comment by schapirama** [comment]
Excellent --thanks for the quick response, @capistrant  !   

Were you intending to get #3 merged and create a new JAR file? If so, I'll wait for it ;-)

**Comment by schapirama** [comment]
I suppose that's up to @stephenball1 to review and merge...

**Comment by stephenball1** [comment]
Sorry for the delay on this @capistrant @schapirama! Review is completed and I am verifying the JAR produced now. Will close this issue when it is verified!

**Comment by stephenball1** [comment]
Confirmed the JAR built in #3 is correct, and I also produced a new version for Druid 0.22.1 just in case. Thanks everyone!

**Comment by schapirama** [comment]
Excellent! Thanks @capistrant  for the fix, and @stephenball1 for getting it merged so quickly! (And, by the way, I can confirm that it works)

Much appreciated.
